name: foods_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  get: 4.6.5
  json_annotation: ^4.7.0
  mrx_charts: ^0.1.3
  pretty_dio_logger: ^1.1.1
  retrofit: ^3.3.1
  flutter: 
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  retrofit_generator: ^4.2.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

fonts:
  - family: Overpass
    fonts:
      - asset: fonts/Overpass-Regular.ttf


