name: foods_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  mrx_charts: ^0.1.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

fonts:
  - family: Overpass
    fonts:
      - asset: fonts/Overpass-Regular.ttf


